services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_xe
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle123
    volumes:
      - ./oracle/init:/opt/oracle/scripts/startup

  php-app:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www

