version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_db
    restart: unless-stopped
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: Oracle123!
      APP_USER: admin
      APP_USER_PASSWORD: admin
    volumes:
      - ../database/schema:/opt/oracle/scripts/setup
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
